doctrine:
    dbal:
        host: localhost
        port: 5432
        dbname: library
        user: postgres
        password: ''
        driver: pdo_pgsql
        charset: utf8
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
